apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
  labels:
    app: filebeat
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: filebeat
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9479"
        prometheus.io/scrape: "true"
      labels:
        app: filebeat
        version: 7.4.2
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: devops/filebeat:7.4.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5066
          protocol: TCP
        volumeMounts:
        - mountPath: /home/appuser/filebeat/filebeat.yml
          name: filebeat-config
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /home/appuser/filebeat/data
          name: data
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 101m
            memory: 100Mi
      - image: trustpilot/beat-exporter:0.1.1
        imagePullPolicy: IfNotPresent
        name: filebeat-prometheus-exporter
        ports:
        - containerPort: 9479
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 11m
            memory: 10Mi
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - name: filebeat-config
        configMap:
          name: filebeat
      - hostPath:
          path: /var/lib/filebeat
          type: DirectoryOrCreate
        name: data
