---
apiVersion: v1
kind: Service
metadata:
  name: elk-logstash
  namespace: logging
  labels:
    app: elk-logstash
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash
