apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elk-kibana-es
  namespace: logging
  labels:
    app: elk-kibana-es
    version: 7.4.2
spec:
  serviceName: elk-kibana-es-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: elk-kibana-es
  template:
    metadata:
      labels:
        app: elk-kibana-es
        version: 7.4.2
    spec:
      containers:
      - name: elasticsearch
        image: devops/elasticsearch:7.4.2
        imagePullPolicy: Always
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: elk-kibana-es-vars
        resources:
          limits:
            cpu: 2000m
            memory: 3000Mi
          requests:
            cpu: 100m
            memory: 1024Mi
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /home/appuser/elasticsearch/data
        - name: es-config
          mountPath: /home/appuser/elasticsearch/config/elasticsearch.yml 
          subPath: elasticsearch.yml
      initContainers:
      - name: init-chown
        image: busybox:1.28
        command: ['sh', '-c', 'chown 1000:1000 /data -R && sysctl -w vm.max_map_count=262144']
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: es-config
        configMap:
          name: elk-kibana-es-config
          defaultMode: 511
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elk-kibana-es
        team: devops
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10G
