---
apiVersion: v1
kind: Service
metadata:
  name: elk-kibana-es-headless
  namespace: logging
  labels:
    app: elk-kibana-es
spec:
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  - name: http
    port: 9200
    protocol: TCP
  clusterIP: None
  selector:
    app: elk-kibana-es
