apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elk-es
  namespace: pks
  labels:
    app: elk-es
    role: master
    version: 7.4.2
spec:
  serviceName: elk-es-headless
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: elk-es
      role: master
  template:
    metadata:
      labels:
        app: elk-es
        role: master
        version: 7.4.2
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - master
            topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch
        image: devops/elasticsearch:7.4.2
        imagePullPolicy: Always
        args:
        - -Ecluster.initial_master_nodes=${MASTER_DISCOVERY_SERVICE}
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: elk-es-vars
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /home/appuser/elasticsearch/data
        - name: es-config
          mountPath: /home/appuser/elasticsearch/config/elasticsearch.yml 
      initContainers:
      - name: init-chown
        image: busybox:1.28
        command: ['sh', '-c', 'chown 1000:1000 /data -R && sysctl -w vm.max_map_count=262144']
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: es-config
        configMap:
          name: elk-es-config
          defaultMode: 511
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elk-es
        role: master
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1000G
