apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-es-vars
  namespace: pks
  labels:
    app: elk-es
    role: master
data:
  CLUSTER_NAME: "test-es"
  DISCOVERY_SERVICE: "elk-es-0.elk-es-headless.pks.svc.cluster.local,elk-es-1.elk-es-headless.pks.svc.cluster.local,elk-es-2.elk-es-headless.pks.svc.cluster.local"
  MASTER_DISCOVERY_SERVICE: "elk-es-0.elk-es-headless.pks.svc.cluster.local,elk-es-1.elk-es-headless.pks.svc.cluster.local"
  GATEWAY_EXPECTED_NODES: "2"
  GATEWAY_NODES_RECOVERY: "2"
  MAX_SHARDS_PER_NODES: "5000"
  NETWORK_HOST: "${NODENAME}.elk-es-headless.pks.svc.cluster.local"
  NODE_DATA: "true"
  NODE_INGEST: "true"
  NODE_MASTER: "true"
  NODE_NAME: "${NODENAME}.elk-es-headless.pks.svc.cluster.local"
  PIPELINE_MAX_EVENTS: "10000"
  THREAD_POOL_WRITE_QUEUE_SIZE: "5000"
  HTTP_PORT: "9200-9300"
  TCP_PORT: "9300-9400"
