---
apiVersion: v1
kind: Service
metadata:
  name: es-client-headless
  namespace: logging
  labels:
    app: elk-es
    role: client
spec:
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  - name: http
    port: 9200
    protocol: TCP
  clusterIP: None
  selector:
    app: elk-es
    role: client
---
apiVersion: v1
kind: Service
metadata:
  name: elk-es
  namespace: logging
  labels:
    app: elk-es
    role: client
spec:
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  - name: http
    port: 9200
    protocol: TCP
  selector:
    app: elk-es
    role: client
